spring.application.name=TrainTogether
server.port=8080

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# --- JPA / Hibernate setup ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Thymeleaf Hot-Reload
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Logging
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
g.hibernate=WARN

# Internationalization
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false